const KEY='swim-monitor-simple-v1';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{athletes:[],daily:[],body:[],tests:[]};
let charts=[];
const $=id=>document.getElementById(id);
const today=new Date().toISOString().slice(0,10);
['dailyDate','bodyDate','testDate'].forEach(id=>$(id).value=today);
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function name(id){return db.athletes.find(a=>a.id===id)?.name||'—'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sexLabel(s){return s==='1'?'Feminino':'Masculino'}
function val(x){return x===''||x==null?null:Number(x)}
function opts(sel){sel.innerHTML='<option value="">Selecionar atleta</option>'+db.athletes.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}
function renderAthletes(){ $('athleteRows').innerHTML=db.athletes.map(a=>`<tr><td>${esc(a.name)}</td><td>${sexLabel(a.sex)}</td><td><button class="danger" onclick="delAthlete('${a.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="3">Sem atletas.</td></tr>'; ['dailyAthlete','bodyAthlete','testAthlete','dashAthlete'].forEach(id=>opts($(id))); if(!$('dashAthlete').value&&db.athletes[0])$('dashAthlete').value=db.athletes[0].id }
function renderDaily(){ $('dailyRows').innerHTML=[...db.daily].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${r.date}</td><td>${esc(name(r.athleteId))}</td><td>${r.pseAM??'—'}</td><td>${r.psePM??'—'}</td><td>${r.hr??'—'}</td><td>${r.sleep??'—'}</td><td><button class="danger" onclick="del('daily','${r.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">Sem registos.</td></tr>' }
function renderBody(){ $('bodyRows').innerHTML=[...db.body].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${r.date}</td><td>${esc(name(r.athleteId))}</td><td>${r.mass??'—'} kg</td><td>${r.height??'—'} cm</td><td>${r.sum7.toFixed(1)} mm</td><td>${r.bodyFat.toFixed(2)}%</td><td><button class="danger" onclick="del('body','${r.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">Sem avaliações.</td></tr>' }
function renderTests(){ $('testRows').innerHTML=[...db.tests].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${r.date}</td><td>${esc(name(r.athleteId))}</td><td>${r.cmj1??'—'}</td><td>${r.cmj2??'—'}</td><td>${r.broad1??'—'}</td><td>${r.broad2??'—'}</td><td><button class="danger" onclick="del('tests','${r.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">Sem testes.</td></tr>' }
function del(type,id){if(confirm('Eliminar este registo?')){db[type]=db[type].filter(x=>x.id!==id);save()}}
function delAthlete(id){if(confirm('Eliminar o atleta e todos os seus registos?')){db.athletes=db.athletes.filter(a=>a.id!==id);['daily','body','tests'].forEach(t=>db[t]=db[t].filter(r=>r.athleteId!==id));save()}}
function renderDashboard(){charts.forEach(c=>c.destroy());charts=[];const id=$('dashAthlete').value;const a=db.athletes.find(x=>x.id===id);$('dashEmpty').style.display=a?'none':'block';$('charts').innerHTML='';if(!a)return;const d=db.daily.filter(r=>r.athleteId===id).sort((a,b)=>a.date.localeCompare(b.date));const b=db.body.filter(r=>r.athleteId===id).sort((a,b)=>a.date.localeCompare(b.date));const t=db.tests.filter(r=>r.athleteId===id).sort((a,b)=>a.date.localeCompare(b.date));
const specs=[['PSE AM',d,x=>x.pseAM,'daily'],['PSE PM',d,x=>x.psePM,'daily'],['FC ao acordar',d,x=>x.hr,'daily'],['Qualidade do sono',d,x=>x.sleep,'daily'],['Massa corporal',b,x=>x.mass,'body'],['Estatura',b,x=>x.height,'body'],['Massa gorda',b,x=>x.bodyFat,'body'],['Σ 7 pregas',b,x=>x.sum7,'body'],['CMJ tentativa 1',t,x=>x.cmj1,'tests'],['CMJ tentativa 2',t,x=>x.cmj2,'tests'],['Impulsão horizontal 1',t,x=>x.broad1,'tests'],['Impulsão horizontal 2',t,x=>x.broad2,'tests']];
specs.forEach(([title,arr,fn])=>{const vals=arr.map(x=>fn(x)).filter(x=>x!=null&&x!=='');if(!vals.length)return;const card=document.createElement('div');card.className='chartcard';card.innerHTML=`<h3>${title}</h3><div class="chartwrap"><canvas></canvas></div>`;$('charts').appendChild(card);charts.push(new Chart(card.querySelector('canvas'),{type:'line',data:{labels:arr.map(x=>x.date),datasets:[{label:title,data:arr.map(x=>fn(x)),tension:.25,spanGaps:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:false}}}}))})}
function renderAll(){renderAthletes();renderDaily();renderBody();renderTests();renderDashboard()}
$('athleteForm').onsubmit=e=>{e.preventDefault();db.athletes.push({id:uid(),name:$('athleteName').value.trim(),sex:$('athleteSex').value});e.target.reset();save()}
$('dailyForm').onsubmit=e=>{e.preventDefault();db.daily.push({id:uid(),athleteId:$('dailyAthlete').value,date:$('dailyDate').value,pseAM:val($('pseAM').value),psePM:val($('psePM').value),hr:val($('wakeHR').value),sleep:val($('sleep').value),notes:$('dailyNotes').value});e.target.reset();$('dailyDate').value=today;save()}
$('bodyForm').onsubmit=e=>{e.preventDefault();const a=db.athletes.find(x=>x.id===$('bodyAthlete').value);const folds=[1,2,3,4,5,6,7].map(i=>val($('s'+i).value));const sum7=folds.reduce((s,x)=>s+(x||0),0);if(folds.some(x=>x==null)){alert('Preenche as 7 pregas subcutâneas.');return}const y=Number(a.sex);const bodyFat=10.566+(0.12077*sum7)-(8.057*y)-(2.545*(y**0));db.body.push({id:uid(),athleteId:a.id,date:$('bodyDate').value,mass:val($('mass').value),height:val($('height').value),folds,sum7,bodyFat});e.target.reset();$('bodyDate').value=today;save()}
$('testForm').onsubmit=e=>{e.preventDefault();db.tests.push({id:uid(),athleteId:$('testAthlete').value,date:$('testDate').value,cmj1:val($('cmj1').value),cmj2:val($('cmj2').value),broad1:val($('broad1').value),broad2:val($('broad2').value)});e.target.reset();$('testDate').value=today;save()}
$('dashAthlete').onchange=renderDashboard;
document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(btn.dataset.view).classList.remove('hidden');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(btn.dataset.view==='dashboard')renderDashboard()});
window.del=del;window.delAthlete=delAthlete;document.querySelector('nav button').click();renderAll();
